export const LOAD_CHARACTERS_REQUEST = 'LOAD_CHARACTERS_REQUEST';
export const LOAD_CHARACTERS_SUCCESS = 'LOAD_CHARACTERS_SUCCESS';
export const LOAD_MORE_CHARACTERS_SUCCESS = 'LOAD_MORE_CHARACTERS_SUCCESS';
export const LOAD_CHARACTERS_FAILURE = 'LOAD_CHARACTERS_FAILURE';
