export enum CharacterTypes {
  GET_CHARACTER_LIST_REQUEST = '@character/GET_CHARACTER_LIST_REQUEST',
  GET_CHARACTER_LIST_SUCCESS = '@character/GET_CHARACTER_LIST_SUCCESS',
  GET_CHARS_PAGINATION_REQUEST = '@character/GET_CHARS_PAGINATION_REQUEST',
  GET_CHARS_PAGINATION_SUCCESS = '@character/GET_CHARS_PAGINATION_SUCCESS',
}
